### ISSUE TITLE
have no clue how to use this software, as theres no guides or instructions.

### ISSUE THREAD

**Issue by TinyGamer** [XAYRGA/JaiSeqX#2]
I'm really interested in using this software, but have no idea how to use it, tried copying the "Seqs" and "Banks" folders from my copy of Luigi's Mansion to the root to no avail, i'm pretty sure i installed all the necessary drivers but it still doesn't work. a readme file on how to use the software would be greatly appreciated.

**Comment by XAYRGA** [comment]
hi
for this to work you have to extract the bms files from the .arc file in the seqs folder.

**currently i'm not making a guide because this is still technically a work in progress, it's almost time for a rewrite and things are going to change significantly.** 

but the basic syntax i think is already in the .exe / command line


```jaiseqxlja.exe <init file> <'play' or 'visu'> "<path to .bms/.com file>" <system version number>```

For example, to play boolossus' theme, after extracting the .arc to a folder named "luigiseq" and putting it in the same folder as the application.

```jaiseqxlja.exe jaiinit.aaf visu "luigiseq/telesabattle.bms" 0``` 

There's also this short thing I made for someone that describes some parameters.

```Don't want the music starting immediately?
-paused 

Want to play out of a different speaker?
-jdsp.device <number>

Start with particular tracks muted?
-mute "1,2,3,4,5" 
if you want to mute child tracks, use the . version of them, eg
 -mute '0.0,0.1,1.1,1.2'.

Playing pikmin 1 music? You'll need this
--jdsp.forcemap_ibnk_bx <number> 
```

**Comment by TinyGamer** [comment]
this was honestly a big help, was able to get it running, really appreciate it! btw what program do you use to extract .arc files? i extracted the .bms files from luigis mansion forever ago and cant remember what i used.

**Comment by XAYRGA** [comment]
No problem!

As for extracting the BARC (.arc) --

1. I maintain tooling for modifying the sound system in luigi's mansion , which extracts the sequences automatically when used.
https://www.xayr.gay/tools/SoundModdingToolkit/7.0.0_EXPERIMENTAL/

Inside the luigi's mansion zip there's a PDF inside "_readme + source code" with a guide on how to install it into the game root, should start on page 10. It should create an audio_modding folder if installed properly, and it will make a "sequences" folder, with the BMS' inside. 

OR

2. I maintain other tooling for manually manipulating the .aaf, and associated tooling for extracting the barc individually.
You'll have to use this 
https://github.com/XAYRGA/jampacked
to unpack the .aaf , find the .hed / BARC in it (might be .arc)

then you can unpack the seqs/jaiarcs.arc with this 

https://github.com/XAYRGA/BARCPack/

**Comment by TinyGamer** [comment]
gonna close the issue, thank you very much!

**Comment by TinyGamer** [comment]
gonna close the issue, thank you very much!

**Comment by dougy2shoez** [comment]
![Image](https://github.com/user-attachments/assets/132d872d-f8b8-4ffd-8f63-ecd650346eb3)
hi im kinda dumb, where am i supposed to put this ?
